on: [push]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: ./output
